[supervisord]
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:celery_judge]
directory=%(here)s
command=celery -A oj.celery worker --loglevel=info -Q celery
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/noj_celery_judge_stdout.log
stderr_logfile=/tmp/noj_celery_judge_stderr.log

[program:celery_agent]
directory=%(here)s
command=celery -A oj.celery worker --loglevel=info -Q agent -c 1
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/noj_celery_agent_stdout.log
stderr_logfile=/tmp/noj_celery_agent_stderr.log

[program:celery_agent_judge]
directory=%(here)s
command=celery -A oj.celery worker --loglevel=info -Q judge -c 2
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/noj_celery_agent_judge_stdout.log
stderr_logfile=/tmp/noj_celery_agent_judge_stderr.log

[group:celery]
programs=celery_judge,celery_agent,celery_agent_judge
