MAIL_SERVER = 'YOUR SMTP SERVER ADDRESS'
MAIL_PORT = 465
MAIL_USERNAME = 'YOUR EMAIL ADDRESS'
MAIL_PASSWORD = 'YOUR SMTP AUTHORIZE CODE'

MYSQL_USERNAME = 'YOUR MYSQL USERNAME'
MYSQL_PASSWORD = 'YOUR MUSQL PASSWORD'

DASHSCOPE_APP_ID = "YOUR ALIYUN DASHSCOPE APP ID"
DASHSCOPE_API_KEY = "YOUR API KEY"

# Agent 自动解题最大迭代轮数
AGENT_MAX_ROUNDS = 3
