MAIL_SERVER = 'YOUR SMTP SERVER ADDRESS'
MAIL_PORT = 465
MAIL_USERNAME = 'YOUR EMAIL ADDRESS'
MAIL_PASSWORD = 'YOUR SMTP AUTHORIZE CODE'

MYSQL_USERNAME = 'YOUR MYSQL USERNAME'
MYSQL_PASSWORD = 'YOUR MUSQL PASSWORD'

DASHSCOPE_APP_ID = "YOUR ALIYUN DASHSCOPE APP ID"
DASHSCOPE_API_KEY = "YOUR API KEY"
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
QWEN_CODER_MODEL = "qwen3-coder-plus"
QWEN_TEXT_MODEL = "qwen3.5-plus"

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 0

# Agent 自动解题最大迭代轮数
AGENT_MAX_ROUNDS = 8
AGENT_MEMORY_ENABLED = True
AGENT_CONTEXT_MAX_CHARS = 48000
AGENT_CONTEXT_KEEP_ROUNDS = 5
AGENT_MEMORY_MAX_PATTERNS = 24
AGENT_MEMORY_MAX_NOTES = 24
AGENT_MEMORY_MAX_DO_NOT_REPEAT = 24
AGENT_CONTEXT_SUMMARY_TIMEOUT = 120
AGENT_CONTEXT_SUMMARY_INPUT_MAX_CHARS = 48000
AGENT_CONTEXT_SUMMARY_OUTPUT_MAX_CHARS = 2400
