MAIL_SERVER = 'YOUR SMTP SERVER ADDRESS'
MAIL_PORT = 465
MAIL_USERNAME = 'YOUR EMAIL ADDRESS'
MAIL_PASSWORD = 'YOUR SMTP AUTHORIZE CODE'

MYSQL_USERNAME = 'YOUR MYSQL USERNAME'
MYSQL_PASSWORD = 'YOUR MUSQL PASSWORD'
MYSQL_CONNECT_TIMEOUT = 5
MYSQL_POOL_MIN_SIZE = 2
MYSQL_POOL_MAX_SIZE = 6
MYSQL_POOL_WAIT_TIMEOUT = 3
MYSQL_POOL_RECYCLE_SECONDS = 1200

DASHSCOPE_APP_ID = "YOUR ALIYUN DASHSCOPE APP ID"
DASHSCOPE_API_KEY = "YOUR API KEY"
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"

# matlab-ai-detect 专用检测模型（本地 vLLM 部署）
# 模型训练完成、vLLM 启动后将 API_KEY 改为任意非空字符串（vLLM 不校验 key）
MATLAB_AI_DETECT_API_KEY = "YOUR_MATLAB_AI_DETECT_API_KEY"
MATLAB_AI_DETECT_URL = "http://127.0.0.1:8000/v1"
MATLAB_AI_DETECT_MODEL = "matlab-ai-detect"

QWEN_CODER_MODEL = "qwen3-coder-plus"
QWEN_TEXT_MODEL = "qwen3.5-plus"
AI_TUTOR_MODEL = "qwen3.5-flash"
QWEN_OMNI_MODEL = "qwen3-vl-flash"
AI_CODE_MARKS_IMAGE_ANALYSIS_TIMEOUT = 180

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 0

SUBMISSION_SNAPSHOT_TTL_SECONDS = 21600
EVALUATE_SUBMISSION_LOCK_TTL_SECONDS = 900

REPOSITORY_EMBEDDING_DIM = 1024
REPOSITORY_SENTENCE_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
REPOSITORY_QWEN_EMBEDDING_MODEL = "text-embedding-v4"
REPOSITORY_EMBEDDING_PROVIDER = "qwen_embedding"
REPOSITORY_STRUCTURED_MODEL = "qwen3.5-plus"
REPOSITORY_STRUCTURED_TIMEOUT = 240
REPOSITORY_STRUCTURED_MAX_INPUT_CHARS = 120000
REPOSITORY_EMBEDDING_TIMEOUT = 120
REPOSITORY_EMBEDDING_BATCH_SIZE = 16
REPOSITORY_VECTOR_BACKEND = "faiss"
REPOSITORY_FAISS_INDEX_ROOT = "tmp/repository_vector_index"

LATEX_OCR_MAX_IMAGES_PER_REQUEST = 20
LATEX_OCR_STREAM_EMIT_INTERVAL = 0.6
LATEX_OCR_STREAM_EMIT_MIN_DELTA = 60

AGENT_MAX_ROUNDS = 32
AGENT_SUBMIT_LIMIT = 8
AGENT_MEMORY_ENABLED = True
AGENT_CONTEXT_MAX_CHARS = 480000
AGENT_CONTEXT_KEEP_ROUNDS = 50
AGENT_MEMORY_MAX_PATTERNS = 24
AGENT_MEMORY_MAX_NOTES = 24
AGENT_MEMORY_MAX_DO_NOT_REPEAT = 24
AGENT_REPOSITORY_KNN_TOP_K = 5
AGENT_REPOSITORY_KNN_SCORE_THRESHOLD = 0.08
AGENT_CONTEXT_SUMMARY_TIMEOUT = 120
AGENT_CONTEXT_SUMMARY_INPUT_MAX_CHARS = 480000
AGENT_CONTEXT_SUMMARY_OUTPUT_MAX_CHARS = 48000

# ModelScope MCP 网页搜索（来自 ModelScope MCP 列表的 Aasee1/open-webSearch）
MODELSCOPE_WEB_SEARCH_MCP_COMMAND = "npx"
MODELSCOPE_WEB_SEARCH_MCP_ARGS = ["-y", "open-websearch@1.2.5"]
MODELSCOPE_WEB_SEARCH_MCP_TOOL_NAME = "search"
MODELSCOPE_WEB_SEARCH_DEFAULT_ENGINES = ["baidu"]
MODELSCOPE_WEB_SEARCH_TIMEOUT_SECONDS = 90
