"""代码仓库索引的共享默认配置。"""

from config import AGENT_REPOSITORY_KNN_SCORE_THRESHOLD, AGENT_REPOSITORY_KNN_TOP_K


try:
    DEFAULT_SEARCH_TOP_K = max(1, int(AGENT_REPOSITORY_KNN_TOP_K))
except Exception:
    DEFAULT_SEARCH_TOP_K = 1

try:
    DEFAULT_SEARCH_SCORE_THRESHOLD = float(AGENT_REPOSITORY_KNN_SCORE_THRESHOLD)
except Exception:
    DEFAULT_SEARCH_SCORE_THRESHOLD = 0.0


__all__ = ["DEFAULT_SEARCH_SCORE_THRESHOLD", "DEFAULT_SEARCH_TOP_K"]
