# CI-only config. Copied to /app/config.py inside the test image.
# Self-contained: must NOT import from `config`.

# MySQL —— 指向 docker-compose 的 mysql 服务
MYSQL_HOST = 'mysql'
MYSQL_PORT = 3306
MYSQL_DB = 'myojdb_test'
MYSQL_USERNAME = 'root'
MYSQL_PASSWORD = 'ci_root_password'
MYSQL_CONNECT_TIMEOUT = 5
MYSQL_POOL_MIN_SIZE = 2
MYSQL_POOL_MAX_SIZE = 6
MYSQL_POOL_WAIT_TIMEOUT = 3
MYSQL_POOL_RECYCLE_SECONDS = 1200

AI_CODE_MARKS_IMAGE_ANALYSIS_TIMEOUT = 180

# Redis —— 指向 docker-compose 的 redis 服务
REDIS_HOST = "redis"
REDIS_PORT = 6379
REDIS_DB = 15

SUBMISSION_SNAPSHOT_TTL_SECONDS = 21600
EVALUATE_SUBMISSION_LOCK_TTL_SECONDS = 900

REPOSITORY_STORAGE_ROOT = "repository_storage"
REPOSITORY_MAX_FILE_BYTES = 2097152
REPOSITORY_MAX_TOTAL_BYTES = 33554432
REPOSITORY_MAX_ENTRIES = 10000
REPOSITORY_MAX_DEPTH = 32
REPOSITORY_MAX_PATH_BYTES = 1024
REPOSITORY_UPLOAD_SESSION_TTL_SECONDS = 86400
REPOSITORY_EMBEDDING_DIM = 1024
REPOSITORY_STRUCTURED_TIMEOUT = 240
REPOSITORY_STRUCTURED_MAX_INPUT_CHARS = 120000
REPOSITORY_EMBEDDING_TIMEOUT = 120
REPOSITORY_EMBEDDING_BATCH_SIZE = 16
REPOSITORY_VECTOR_BACKEND = "faiss"
REPOSITORY_FAISS_INDEX_ROOT = "tmp/repository_vector_index"

LATEX_OCR_MAX_IMAGES_PER_REQUEST = 20
LATEX_OCR_STREAM_EMIT_INTERVAL = 0.6
LATEX_OCR_STREAM_EMIT_MIN_DELTA = 60

AGENT_REPOSITORY_KNN_TOP_K = 5
AGENT_REPOSITORY_KNN_SCORE_THRESHOLD = 0.08
AGENT_WORKSPACE_ROOT = "tmp/agent_workspaces"
AGENT_CONTAINER_SITE_URL = "http://host.docker.internal:2025"
AGENT_JUDGE_DOCKER_IMAGE = "numericaloj-agent-judge-lite:latest"
AGENT_JUDGE_DEFAULT_TIMEOUT = 1800
AGENT_JUDGE_MEM_LIMIT = "4g"
AGENT_JUDGE_CPU_LIMIT = "2"
AGENT_JUDGE_PIDS_LIMIT = "512"

JUDGER_DOCKER_RUNNER_UID = 65532
JUDGER_DOCKER_RUNNER_GID = 65532
JUDGER_DOCKER_CASE_TMPFS_BYTES = 134217728
JUDGER_DOCKER_EXPORT_TMPFS_BYTES = 100663296
JUDGER_CASE_INPUT_MAX_BYTES = 67108864
JUDGER_STDOUT_MAX_BYTES = 1048576
JUDGER_STDERR_MAX_BYTES = 1048576

MODELSCOPE_WEB_SEARCH_TIMEOUT_SECONDS = 90
