#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LLM-based AI code detection for MATLAB submissions.

Sends the student code + problem description to Qwen and asks it to judge
whether the code was likely generated by an AI assistant.
"""

import json
import re
import time

_MAX_RETRIES = 3
_RETRY_DELAY = 3  # seconds between retries


class LLMDetectionFailed(Exception):
    pass

from config import (
    CODING_PLAN_KEY,
    CODING_PLAN_URL,
    QWEN_TEXT_MODEL,
)

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

_SYSTEM_PROMPT = """\
你是一位经验丰富的大学编程课教师，擅长识别学生提交的 MATLAB 代码是否由 AI（如 ChatGPT、通义千问、Copilot 等）生成。

请你根据以下特征综合判断代码由 AI 生成的概率：

**AI 生成代码的常见特征（MATLAB）：**
1. 注释过于规范和冗长，几乎每一步都有说明性注释，注释用词"教科书式"（如 "Initialize ...", "Ensure ...", "Calculate ..."）
2. 变量命名过于规范和描述性（如 coefficientMatrix、resultVector），不像学生常用的短变量名（如 A、b、x、res）
3. 喜欢把自己当成一个 “助手”，而不是一个 “解决问题的人”，会留下一些形如 “已完成修改”、“已修复xxx问题”、“已添加xxx功能” 诸如此类的注释
4. 包含超出课程水平的错误处理（try-catch + 详细错误提示）
5. 使用了学生通常不会用到的高级写法或内置函数
6. 代码组织方式像是"回答问题"而非"解决问题"——先解释再写代码
7. 注释和代码中英文混排，但英文部分流畅度异常高
8. 注释里面包含除英文、中文、中英文标点符号之外的其它符号，尤其是希腊字母、特殊的数学符号等等，这些符号不容易用键盘与输入法打出来

**学生手写代码的常见特征：**
1. 注释稀少或只有关键处有简短注释
2. 变量名简短，常用单字母或缩写（i, j, n, A, b）
3. 直接解决问题，没有多余的"框架性"代码
4. 可能有试错痕迹（注释掉的代码、调试输出）

请严格输出以下 JSON 格式（不要输出其他内容）：
{
  "ai_probability": <0.0 到 1.0 的浮点数>,
  "confidence": <你对自己判断的置信度，0.0 到 1.0>,
  "evidence": [<最多 5 条判断依据，每条是一个字符串>]
}
"""

_USER_PROMPT_TEMPLATE = """\
## 题目描述
{problem_description}

## 学生提交的代码
```matlab
{code}
```

请判断这段代码由 AI 生成的概率。"""


def _is_invalid_secret(value):
    text = str(value or "").strip()
    return (not text) or ("YOUR" in text.upper())


def _sanitize_json(raw):
    """Replace unescaped newlines inside JSON string values so json.loads can parse."""
    # Replace literal newlines/tabs inside quoted strings with their escape sequences
    def _fix_string(m):
        return m.group(0).replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
    return re.sub(r'"(?:[^"\\]|\\.)*"', _fix_string, raw, flags=re.DOTALL)


def _parse_llm_response(text):
    """Extract JSON from LLM response, handling markdown code fences."""
    raw = str(text or "").strip()
    if not raw:
        return None

    # Strip markdown code fences
    match = re.search(r"```(?:json)?\s*\n?(.*?)```", raw, re.DOTALL)
    if match:
        raw = match.group(1).strip()

    for candidate in (raw, _sanitize_json(raw)):
        try:
            result = json.loads(candidate)
            break
        except json.JSONDecodeError:
            pass
    else:
        # Last resort: extract the JSON object containing ai_probability
        match = re.search(r"\{[^{}]*\"ai_probability\"[^{}]*\}", raw, re.DOTALL)
        if match:
            try:
                result = json.loads(_sanitize_json(match.group(0)))
            except json.JSONDecodeError:
                return None
        else:
            return None

    prob = result.get("ai_probability")
    if prob is None:
        return None
    try:
        prob = float(prob)
    except (TypeError, ValueError):
        return None

    prob = max(0.0, min(1.0, prob))
    confidence = max(0.0, min(1.0, float(result.get("confidence", 0.5))))
    evidence = result.get("evidence", [])
    if not isinstance(evidence, list):
        evidence = []
    evidence = [str(e) for e in evidence[:5]]

    return {
        "ai_probability": prob,
        "confidence": confidence,
        "evidence": evidence,
    }


def detect_with_llm(code, problem_description=""):
    """
    Use LLM to estimate the probability that the given MATLAB code is AI-generated.

    Returns:
        dict with keys: score (float 0~1), evidence (list[str]), raw_response (str)
        Returns None if the API call fails.
    """
    if OpenAI is None:
        print("[AI Detection] openai package not installed, skipping LLM detection")
        return None

    if _is_invalid_secret(CODING_PLAN_KEY):
        print("[AI Detection] CODING_PLAN_KEY not configured, skipping LLM detection")
        return None

    base_url = str(CODING_PLAN_URL or "").strip().rstrip("/")
    if not base_url:
        return None

    model = str(QWEN_TEXT_MODEL or "").strip()
    if not model:
        return None

    user_prompt = _USER_PROMPT_TEMPLATE.format(
        problem_description=problem_description[:3000],
        code=code[:8000],
    )

    client = OpenAI(api_key=CODING_PLAN_KEY, base_url=base_url)
    last_error = None

    for attempt in range(1, _MAX_RETRIES + 1):
        raw_text = None
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.3,
                max_tokens=1024,
            )
            raw_text = response.choices[0].message.content or ""
        except Exception as e:
            last_error = f"API call failed: {e}"
            print(f"[AI Detection] {last_error} (attempt {attempt}/{_MAX_RETRIES})")
            if attempt < _MAX_RETRIES:
                time.sleep(_RETRY_DELAY)
            continue

        parsed = _parse_llm_response(raw_text)
        if parsed is None:
            last_error = f"Failed to parse response: {raw_text[:200]}"
            print(f"[AI Detection] {last_error} (attempt {attempt}/{_MAX_RETRIES})")
            if attempt < _MAX_RETRIES:
                time.sleep(_RETRY_DELAY)
            continue

        return {
            "score": parsed["ai_probability"],
            "confidence": parsed["confidence"],
            "evidence": parsed["evidence"],
            "raw_response": raw_text[:2000],
        }

    raise LLMDetectionFailed(f"LLM detection failed after {_MAX_RETRIES} attempts: {last_error}")
