#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LLM-based AI code detection for MATLAB submissions.

Sends the student code + problem description to an LLM and asks it to judge
whether the code was likely generated by an AI assistant.

Supported model_id values:
  - "qwen"              : qwen3.5-plus via CODING_PLAN_KEY / CODING_PLAN_URL
  - "matlab_ai_detect"  : custom fine-tuned model (configured separately)
"""

import json
import re
import time

_MAX_RETRIES = 3
_RETRY_DELAY = 3  # seconds between retries


class LLMDetectionFailed(Exception):
    pass


from config import (
    CODING_PLAN_KEY,
    CODING_PLAN_URL,
    QWEN_TEXT_MODEL,
    MATLAB_AI_DETECT_API_KEY,
    MATLAB_AI_DETECT_URL,
    MATLAB_AI_DETECT_MODEL,
)

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None


# ============================================================
# Qwen 默认模型的 Prompt
# ============================================================

_QWEN_SYSTEM_PROMPT = """\
你是一位经验丰富的大学编程课教师，擅长识别学生提交的 MATLAB 代码是否由 AI（如 ChatGPT、通义千问、Copilot 等）生成。

请你根据以下特征综合判断代码由 AI 生成的概率：

**AI 生成代码的常见特征（MATLAB）：**
1. 注释过于规范和冗长，几乎每一步都有说明性注释，注释用词"教科书式"（如 "Initialize ...", "Ensure ...", "Calculate ..."）
2. 变量命名过于规范和描述性（如 coefficientMatrix、resultVector），不像学生常用的短变量名（如 A、b、x、res）
3. 喜欢把自己当成一个 "助手"，而不是一个 "解决问题的人"，会留下一些形如 "已完成修改"、"已修复xxx问题"、"已添加xxx功能" 诸如此类的注释
4. 包含超出课程水平的错误处理（try-catch + 详细错误提示）
5. 使用了学生通常不会用到的高级写法或内置函数
6. 代码组织方式像是"回答问题"而非"解决问题"——先解释再写代码
7. 注释和代码中英文混排，但英文部分流畅度异常高
8. 注释里面包含除英文、中文、中英文标点符号之外的其它符号，尤其是希腊字母、特殊的数学符号等等，这些符号不容易用键盘与输入法打出来

**学生手写代码的常见特征：**
1. 注释稀少或只有关键处有简短注释
2. 变量名简短，常用单字母或缩写（i, j, n, A, b）
3. 直接解决问题，没有多余的"框架性"代码
4. 可能有试错痕迹（注释掉的代码、调试输出）

请严格输出以下 JSON 格式（不要输出其他内容）：
{
  "ai_probability": <0.0 到 1.0 的浮点数>,
  "confidence": <你对自己判断的置信度，0.0 到 1.0>,
  "evidence": [<最多 5 条判断依据，每条是一个字符串>]
}
"""

_QWEN_USER_PROMPT_TEMPLATE = """\
## 题目描述
{problem_description}

## 学生提交的代码
```matlab
{code}
```

请判断这段代码由 AI 生成的概率。"""


# ============================================================
# matlab-ai-detect 专用 Prompt
# ============================================================

# 该模型使用 RL 训练，不使用 system prompt
_MATLAB_AI_DETECT_SYSTEM_PROMPT = None

_MATLAB_AI_DETECT_USER_PROMPT_TEMPLATE = (
    "请分析以下 MATLAB 代码，判断它是由 AI 生成的还是由人类手写的。\n"
    "请给出你的分析过程，并将最终答案放在 \\boxed{{}} 中（只填写 ai 或 human）。\n\n"
    "```matlab\n{code}\n```"
)


# ============================================================
# 响应解析
# ============================================================

def _parse_boxed_response(text):
    """
    Parse matlab-ai-detect model output.
    The model outputs a reasoning chain ending with \\boxed{ai} or \\boxed{human}.
    Maps: ai -> 1.0, human -> 0.0
    """
    raw = str(text or "").strip()
    if not raw:
        return None
    match = re.search(r"\\boxed\{(ai|human)\}", raw, re.IGNORECASE)
    if not match:
        return None
    label = match.group(1).lower()
    return {
        "ai_probability": 1.0 if label == "ai" else 0.0,
        "confidence": 1.0,
        "evidence": [],
    }


def _is_invalid_secret(value):
    text = str(value or "").strip()
    return (not text) or ("YOUR" in text.upper())


def _sanitize_json(raw):
    """Replace unescaped newlines inside JSON string values so json.loads can parse."""
    def _fix_string(m):
        return m.group(0).replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
    return re.sub(r'"(?:[^"\\]|\\.)*"', _fix_string, raw, flags=re.DOTALL)


def _parse_llm_response(text):
    """Extract JSON from LLM response, handling markdown code fences."""
    raw = str(text or "").strip()
    if not raw:
        return None

    # Strip markdown code fences
    match = re.search(r"```(?:json)?\s*\n?(.*?)```", raw, re.DOTALL)
    if match:
        raw = match.group(1).strip()

    for candidate in (raw, _sanitize_json(raw)):
        try:
            result = json.loads(candidate)
            break
        except json.JSONDecodeError:
            pass
    else:
        match = re.search(r"\{[^{}]*\"ai_probability\"[^{}]*\}", raw, re.DOTALL)
        if match:
            try:
                result = json.loads(_sanitize_json(match.group(0)))
            except json.JSONDecodeError:
                return None
        else:
            return None

    prob = result.get("ai_probability")
    if prob is None:
        return None
    try:
        prob = float(prob)
    except (TypeError, ValueError):
        return None

    prob = max(0.0, min(1.0, prob))
    confidence = max(0.0, min(1.0, float(result.get("confidence", 0.5))))
    evidence = result.get("evidence", [])
    if not isinstance(evidence, list):
        evidence = []
    evidence = [str(e) for e in evidence[:5]]

    return {
        "ai_probability": prob,
        "confidence": confidence,
        "evidence": evidence,
    }


# ============================================================
# 可用性检测
# ============================================================

def is_matlab_ai_detect_available():
    """Return True only if matlab-ai-detect API key and URL are properly configured."""
    return (
        not _is_invalid_secret(MATLAB_AI_DETECT_API_KEY)
        and bool(str(MATLAB_AI_DETECT_URL or "").strip())
        and "YOUR" not in str(MATLAB_AI_DETECT_URL or "").upper()
        and bool(str(MATLAB_AI_DETECT_MODEL or "").strip())
    )


def get_available_models():
    """Return list of available model dicts for the frontend."""
    models = [
        {"id": "qwen", "name": "Qwen3.5-Plus（默认）", "available": True},
    ]
    models.append({
        "id": "matlab_ai_detect",
        "name": "MATLAB-AI-Detect（专用模型）",
        "available": is_matlab_ai_detect_available(),
    })
    return models


# ============================================================
# 核心检测函数
# ============================================================

def _call_openai_api(api_key, base_url, model, system_prompt, user_prompt,
                     response_parser=None, temperature=0.3, max_tokens=1024):
    """Call OpenAI-compatible chat API and parse the response.

    Args:
        response_parser: callable(raw_text) -> parsed dict, or None to use
                         the default JSON parser (_parse_llm_response).
    """
    if response_parser is None:
        response_parser = _parse_llm_response

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": user_prompt})

    client = OpenAI(api_key=api_key, base_url=base_url)
    last_error = None

    for attempt in range(1, _MAX_RETRIES + 1):
        raw_text = None
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            raw_text = response.choices[0].message.content or ""
        except Exception as e:
            last_error = f"API call failed: {e}"
            print(f"[AI Detection] {last_error} (attempt {attempt}/{_MAX_RETRIES})")
            if attempt < _MAX_RETRIES:
                time.sleep(_RETRY_DELAY)
            continue

        parsed = response_parser(raw_text)
        if parsed is None:
            last_error = f"Failed to parse response: {raw_text[:200]}"
            print(f"[AI Detection] {last_error} (attempt {attempt}/{_MAX_RETRIES})")
            if attempt < _MAX_RETRIES:
                time.sleep(_RETRY_DELAY)
            continue

        return {
            "score": parsed["ai_probability"],
            "confidence": parsed["confidence"],
            "evidence": parsed["evidence"],
            "raw_response": raw_text[:2000],
        }

    raise LLMDetectionFailed(
        f"LLM detection failed after {_MAX_RETRIES} attempts: {last_error}"
    )


def detect_with_llm(code, problem_description="", model_id="qwen"):
    """
    Use LLM to estimate the probability that the given MATLAB code is AI-generated.

    Args:
        code: MATLAB source code string
        problem_description: problem statement text
        model_id: "qwen" (default) or "matlab_ai_detect"

    Returns:
        dict with keys: score (float 0~1), evidence (list[str]), raw_response (str)
        Returns None if the API is not configured (skips silently).
        Raises LLMDetectionFailed if the API is configured but the call fails.
    """
    if OpenAI is None:
        print("[AI Detection] openai package not installed, skipping LLM detection")
        return None

    if model_id == "matlab_ai_detect":
        if not is_matlab_ai_detect_available():
            print("[AI Detection] matlab-ai-detect not configured, skipping")
            return None
        api_key = str(MATLAB_AI_DETECT_API_KEY).strip()
        base_url = str(MATLAB_AI_DETECT_URL).strip().rstrip("/")
        model = str(MATLAB_AI_DETECT_MODEL).strip()
        system_prompt = _MATLAB_AI_DETECT_SYSTEM_PROMPT  # None：不传 system prompt
        user_prompt = _MATLAB_AI_DETECT_USER_PROMPT_TEMPLATE.format(code=code[:8000])
        return _call_openai_api(
            api_key, base_url, model, system_prompt, user_prompt,
            response_parser=_parse_boxed_response,
            temperature=0.0,   # RL 模型推理时用贪心解码
            max_tokens=4096,   # 需要输出完整推理链
        )
    else:
        # Default: qwen
        if _is_invalid_secret(CODING_PLAN_KEY):
            print("[AI Detection] CODING_PLAN_KEY not configured, skipping LLM detection")
            return None
        base_url = str(CODING_PLAN_URL or "").strip().rstrip("/")
        if not base_url:
            return None
        model = str(QWEN_TEXT_MODEL or "").strip()
        if not model:
            return None
        api_key = str(CODING_PLAN_KEY).strip()
        system_prompt = _QWEN_SYSTEM_PROMPT
        user_prompt = _QWEN_USER_PROMPT_TEMPLATE.format(
            problem_description=problem_description[:3000],
            code=code[:8000],
        )

    return _call_openai_api(api_key, base_url, model, system_prompt, user_prompt)
