export const problemInsights = [
  ['General methods that leverage computation are ultimately the most effective, and by a large margin.', '充分利用计算能力的通用方法，归根结底总是最有效的，而且优势往往非常显著。', 'Rich Sutton'],
  ['Intelligence is the efficiency with which a learning system turns experience and priors into skill at previously unknown tasks.', '智能，是学习系统将经验与先验转化为应对未知任务之技能的效率。', 'François Chollet'],
  ['The hottest new programming language is English.', '最热门的新编程语言是英语。', 'Andrej Karpathy'],
  ['When people say 99% of their code is written by AI, I pretty much guarantee that 100% of it is written by compilers.', '当有人说自己的代码 99% 由 AI 编写时，我几乎可以断定，其中 100% 都是由编译器写成的。', 'Linus Torvalds'],
  ['Linux is not one of those anti-AI projects, and if somebody has issues with that, they can do the open-source thing and fork it.', 'Linux 不是那种反 AI 项目；如果有人对此不满，大可以按开源的方式 fork 它。', 'Linus Torvalds'],
  ['The programming language is human: everybody in the world is now a programmer—that is the miracle.', '编程语言就是人类语言：世界上的每个人如今都是程序员——这才是奇迹。', 'Jensen Huang'],
  ['Despite its name, there is nothing ‘artificial’ about this technology—it is made by humans, intended to behave like humans and affects humans.', '尽管名为“人工智能”，这项技术并非凭空而来——它由人创造、旨在表现得像人，并影响着人。', 'Fei-Fei Li'],
  ['Productive use of coding agents requires confidently instructing them and confidently verifying the changes they make.', '高效使用编程智能体，需要既能自信地向它们下达指令，也能自信地验证它们所做的修改。', 'Simon Willison'],
  ['We have the same exact bar regardless of whether the code was written by the model or by a human.', '无论代码由模型还是人编写，我们采用的标准都完全相同。', 'Boris Cherny · Anthropic'],
  ['Large populations of agents somewhere in the cloud that we as humanity, as people, teams, organizations supervise and steer.', '云端将存在庞大的智能体群体，由我们人类以个人、团队和组织的形式进行监督与引导。', 'Thibault ‘Tibo’ Sottiaux · OpenAI'],
  ['Agents are not only going to change how everyone interacts with computers. They’re also going to upend the software industry.', '智能体不仅会改变每个人与计算机交互的方式，还将彻底重塑软件行业。', 'Bill Gates'],
  ['Eventually we can each have a personal AI team, full of virtual experts in different areas.', '最终，我们每个人都能拥有一支私人 AI 团队，成员是来自不同领域的虚拟专家。', 'Sam Altman'],
  ['As AI and agents take on more of the execution, the opportunity is to expand human agency and redesign how work gets done.', '随着 AI 和智能体承担更多执行工作，真正的机会在于扩展人的能动性，并重新设计工作的方式。', 'Satya Nadella'],
  ['AI tools will allow the best to reach even greater heights, while enabling smaller teams to accomplish more.', 'AI 工具会让最优秀的人攀上更高峰，也让更小的团队完成更多事情。', 'John Carmack'],
  ['Humans are still responsible for what the software does and how it works, but use different skills to create their products.', '人类依然要对软件做什么、如何运作负责，只是会用不同的技能来创造产品。', 'Martin Fowler'],
  ['As long as the output is correct, maintainable, and legible to future agent runs, it meets the bar.', '只要产出正确、可维护，并能被后续运行的智能体清晰理解，它就达到了标准。', 'Ryan Lopopolo · OpenAI'],
  ['Grade the outcome, not the claim.', '评判结果，而不是它的自我陈述。', 'Mikaela Grace et al. · Anthropic'],
  ['A few-point lead might signal a real capability gap—or it might just be a bigger VM.', '领先几分，可能代表真实的能力差距——也可能只是评测时用了配置更高的虚拟机。', 'Gian Segato · Anthropic'],
] as const

export const frontierProjects = [
  'openai/codex', 'badlogic/pi-mono', 'anomalyco/opencode', 'deepseek-ai/deepseek-harness', 'OpenHands/OpenHands', 'Aider-AI/aider', 'aaif-goose/goose', 'SWE-agent/mini-swe-agent', 'NousResearch/hermes-agent', 'QwenLM/qwen-code', 'cline/cline', 'RooCodeInc/Roo-Code', 'continuedev/continue', 'SWE-agent/SWE-agent', 'huggingface/smolagents',
  'NVIDIA/Megatron-LM', 'deepspeedai/DeepSpeed', 'huggingface/trl', 'verl-project/verl', 'axolotl-ai-cloud/axolotl', 'unslothai/unsloth', 'hiyouga/LlamaFactory', 'modelscope/ms-swift', 'OpenRLHF/OpenRLHF', 'NVIDIA-NeMo/RL', 'THUDM/slime', 'areal-project/AReaL', 'agentica-project/rllm', 'allenai/open-instruct', 'huggingface/open-r1', 'Lightning-AI/litgpt',
  'vllm-project/vllm', 'sgl-project/sglang', 'ggml-org/llama.cpp', 'NVIDIA/TensorRT-LLM', 'InternLM/lmdeploy', 'mlc-ai/mlc-llm', 'llm-d/llm-d', 'kvcache-ai/Mooncake', 'flashinfer-ai/flashinfer', 'LMCache/LMCache', 'deepseek-ai/FlashMLA', 'deepseek-ai/DeepGEMM',
  'jingyaogong/minimind', 'karpathy/nanoGPT', 'rasbt/LLMs-from-scratch', 'karpathy/nn-zero-to-hero', 'karpathy/micrograd', 'karpathy/makemore', 'karpathy/nanochat', 'karpathy/llama2.c', 'karpathy/llm.c',
  'microsoft/AI-For-Beginners', 'microsoft/ML-For-Beginners', 'microsoft/generative-ai-for-beginners', 'microsoft/ai-agents-for-beginners', 'huggingface/agents-course', 'huggingface/course', 'DatawhaleChina/happy-llm', 'DatawhaleChina/llm-universe', 'DatawhaleChina/self-llm', 'd2l-ai/d2l-zh', 'labmlai/annotated_deep_learning_paper_implementations',
  'leanprover/lean4', 'leanprover-community/mathlib4', 'leanprover-community/mathematics_in_lean', 'leanprover-community/aesop', 'lean-dojo/LeanDojo-v2', 'lean-dojo/LeanCopilot', 'deepseek-ai/DeepSeek-Prover-V2', 'project-numina/numina-lean-agent', 'project-numina/kimina-lean-server',
  'krahets/hello-algo', 'algorithm-visualizer/algorithm-visualizer', 'OpenDSA/OpenDSA',
] as const
