const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '..')
const source = (relativePath) => fs.readFileSync(path.join(frontendRoot, relativePath), 'utf8')

test('代码仓库保留 Jinja 版安全保存、内部拖拽和完整上传会话', () => {
  const repository = source('src/pages/RepositoryPage.tsx')
  assert.match(repository, /saveInFlightRef/)
  assert.match(repository, /addCommand\?\.\(saveBinding/)
  assert.match(repository, /persistBeforeTransition/)
  assert.match(repository, /addEventListener\('beforeunload'/)
  assert.match(repository, /application\/x-numoj-entry-id/)
  assert.match(repository, /\/api\/repository\/upload\/session/)
  assert.match(repository, /digestSha256\(chunk\)/)
  assert.match(repository, /下载本地备份/)
  assert.match(repository, /丢弃本地修改并重新载入/)
  assert.match(repository, /repositoryIndexJobId/)
  assert.match(repository, /indexJobRunning/)
  assert.match(repository, /结构化整理完成/)
})

test('论坛在 HTTP 下保留 UUID 回退、标签页草稿和冻结重试语义', () => {
  const forum = source('src/pages/ForumPage.tsx')
  const uuid = source('src/lib/browserUuid.ts')
  assert.doesNotMatch(forum, /crypto\.randomUUID\(/)
  assert.match(forum, /browserUuid\(\)/)
  assert.match(uuid, /getRandomValues/)
  assert.match(forum, /window\.sessionStorage/)
  assert.match(forum, /pending_attempt/)
  assert.match(forum, /FORUM_RETRY_DELAYS = \[350, 900, 1800\]/)
  assert.match(forum, /结果尚未确认，内容与请求标识已冻结/)
  assert.match(forum, /useInfiniteQuery/)
  assert.match(forum, /加载更多讨论/)
  assert.match(forum, /加载更早回复/)
  assert.match(forum, /以此草稿重建编辑/)
  assert.match(forum, /posting_identity_changed/)
  assert.match(forum, /cooldown_remaining_seconds/)
  assert.match(forum, /HAN_CODEPOINT_RANGES/)
  assert.match(forum, /匿名用户名的加权长度不能超过 10/)
  assert.match(forum, /enabled && !identity\.data\?\.identity\.anonymous_name/)
  assert.match(forum, /enable: identity\.data\?\.identity\.anonymous_name \? useAnonymous : true/)
})

test('打榜赛恢复 revision 轮询、SSE 自动重连和可撤销编辑', () => {
  const ranking = source('src/pages/RankingDetailPage.tsx')
  const overlays = source('src/ranking/RankingDetailOverlays.tsx')
  assert.match(ranking, /refetchInterval: 10000/)
  assert.match(ranking, /refetchOnWindowFocus: 'always'/)
  assert.match(ranking, /maxOutput > contextWindow/)
  assert.match(ranking, /modalDraft/)
  assert.match(ranking, /setModalDraft\(\{\.\.\.rules\[index\]\}\)/)
  assert.match(overlays, /useRankingEventSnapshot\(url, open, onTerminal, true\)/)
  assert.match(overlays, /if \(reconnect && source\.readyState !== EventSource\.CLOSED\)/)
  assert.match(overlays, /本轮实时连接已结束，正在自动续接评测进度/)
  assert.match(overlays, /\/api\/ranking\/submissions\/\$\{target\.id\}\/reverse-agent-answer/)
})

test('真实评测触发保留入队警告、批量终态与后台结果刷新', () => {
  const ranking = source('src/pages/RankingDetailPage.tsx')
  const appeal = source('src/pages/RankingAppealReviewPage.tsx')
  const detection = source('src/pages/AiDetectionPage.tsx')
  const homework = source('src/pages/HomeworkAdminPage.tsx')
  assert.match(ranking, /pending_confirmation/)
  assert.match(ranking, /warnings\?: Array/)
  assert.match(ranking, /bulkJobTerminal/)
  assert.match(ranking, /last_error/)
  assert.match(ranking, /仓库命名必须包含 <username> 占位符/)
  assert.match(ranking, /查看所有提交/)
  assert.match(appeal, /navigate\(`\/rankings\/\$\{competitionId\}\?tab=all_submissions`\)/)
  assert.match(detection, /refetchInterval: \(query\).*pending.*running.*3000/)
  assert.match(detection, /hadActiveTasks/)
  assert.match(homework, /progressTerminal/)
  assert.match(homework, /autoDownloadedExport/)
})

test('VibeHub Player 保留租约异常恢复与 iframe 就绪屏障', () => {
  const player = source('src/pages/VibeHubPlayerPage.tsx')
  assert.match(player, /error\.status === 429/)
  assert.match(player, /heartbeatFailures < 3/)
  assert.match(player, /15_000/)
  assert.match(player, /heartbeatPromise/)
  assert.match(player, /acquireGeneration/)
  assert.match(player, /navigator\.sendBeacon/)
  assert.match(player, /onLoad=\{\(\) => \{if \(runtime\) setFrameReady\(true\)\}\}/)
})

test('全站配置测试会回写容量并经过原生表单校验', () => {
  const config = source('src/pages/SiteConfigPage.tsx')
  assert.match(config, /reportValidity\(\)/)
  assert.match(config, /context_window_tokens: String\(tested\.context_window_tokens\)/)
  assert.match(config, /max_output_tokens: String\(tested\.max_output_tokens\)/)
  assert.match(config, /if \(result\.limits_adjusted\)/)
  assert.match(config, /test_token: tested\.test_token/)
  assert.match(config, /formRef\.current\?\.reportValidity\(\)/)
  assert.match(config, /setForm\(formFromSettings\(data\.settings\)\)/)
  assert.match(config, /allConfigQueries\.every/)
  assert.match(config, /单次最大输出不得超过上下文窗口/)
  assert.match(config, /基础地址必须使用 HTTP 或 HTTPS/)
})

test('迁移后的辅助页面不会把失败伪装成空数据或成功状态', () => {
  const problems = source('src/pages/ProblemsPage.tsx')
  const repository = source('src/pages/RepositoryPage.tsx')
  const detection = source('src/pages/AiDetectionPage.tsx')
  const submissions = source('src/pages/SubmissionsPage.tsx')
  const problemDetail = source('src/pages/ProblemDetailPage.tsx')
  const ranking = source('src/pages/RankingDetailPage.tsx')
  const shell = source('src/components/AppShell.tsx')
  const filePreview = source('src/pages/agent/AgentFilePreview.tsx')
  const agentTasks = source('src/pages/AgentTasksPage.tsx')
  const agentSession = source('src/pages/AgentSessionPage.tsx')
  const submissionDetail = source('src/pages/SubmissionDetailPage.tsx')
  const rankingOverlays = source('src/ranking/RankingDetailOverlays.tsx')
  const admin = source('src/pages/AdminPage.tsx')

  assert.match(problems, /activity\.isError/)
  assert.match(problems, /暂定，另有提交评测中/)
  assert.match(problems, /shuffledIndexes/)
  assert.match(repository, /file\.isError/)
  assert.match(repository, /重试读取/)
  assert.match(detection, /tasks\.isError/)
  assert.match(submissions, /无法读取重测进度/)
  assert.match(problemDetail, /rejudgeProgressError/)
  assert.match(ranking, /copyText\(data\.git_repo_url/)
  assert.match(shell, /prefetchInfiniteQuery/)
  assert.match(shell, /\['forum', 'list', 'all', ''\]/)
  assert.match(filePreview, /rawText\.refetch\(\)/)
  assert.match(agentTasks, /AgentAccessQueryError/)
  assert.match(agentTasks, /单次最大输出不得超过上下文窗口/)
  assert.match(agentSession, /实时状态连接暂时中断，正在自动重试/)
  assert.match(submissionDetail, /重新检查/)
  assert.match(rankingOverlays, /onClick=\{retry\}>重新加载/)
  assert.match(admin, /result\.refetch\(\)/)
})

test('页面记忆沿用 Jinja 的存储键、账号作用域与服务端启动偏好', () => {
  const session = source('src/session.tsx')
  const problems = source('src/pages/ProblemsPage.tsx')
  const forum = source('src/pages/ForumPage.tsx')
  const agents = source('src/pages/AgentTasksPage.tsx')
  const problemDetail = source('src/pages/ProblemDetailPage.tsx')
  const lean = source('src/components/LeanWorkbench.tsx')
  const shell = source('src/components/AppShell.tsx')
  const repository = source('src/pages/RepositoryPage.tsx')

  assert.match(session, /numoj\.layoutNavigation\.v1/)
  assert.match(session, /payload\.user\.id/)
  assert.match(session, /payload\.navigation\.selected_class_en/)
  assert.match(session, /class_en: selectedClass/)
  assert.match(problems, /numoj\.classActivity\.v1/)
  assert.match(problems, /session\?\.user\?\.id/)
  assert.match(problems, /class_en: classEn, remember: 0/)
  assert.match(problems, /staleTime: 0/)

  assert.match(forum, /numoj\.forum\.v2/)
  assert.match(forum, /draft_namespace/)
  assert.match(agents, /result\.data\?\.preference\?\.harness/)
  assert.match(agents, /result\.data\?\.preference\?\.endpoint_id/)
  assert.match(problemDetail, /options\.data\.preference\?\.harness/)
  assert.match(problemDetail, /options\.data\.preference\?\.endpoint_id/)

  assert.match(shell, /numoj\.desktopSidebarCollapsed/)
  assert.match(problemDetail, /numoj\.problemDetail\.statementRatio/)
  assert.match(problemDetail, /numoj\.problemDetail\.leanStatementRatio/)
  assert.match(lean, /numoj\.problemDetail\.leanSourceRatio/)
  assert.match(repository, /repositoryIndexJobId/)
})
