const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '..')
const source = (relativePath) => fs.readFileSync(path.join(frontendRoot, relativePath), 'utf8')

test('代码仓库保留 Jinja 版安全保存、内部拖拽和完整上传会话', () => {
  const repository = source('src/pages/RepositoryPage.tsx')
  assert.match(repository, /saveInFlightRef/)
  assert.match(repository, /addCommand\?\.\(saveBinding/)
  assert.match(repository, /persistBeforeTransition/)
  assert.match(repository, /addEventListener\('beforeunload'/)
  assert.match(repository, /application\/x-numoj-entry-id/)
  assert.match(repository, /\/api\/repository\/upload\/session/)
  assert.match(repository, /digestSha256\(chunk\)/)
  assert.match(repository, /下载本地备份/)
  assert.match(repository, /丢弃本地修改并重新载入/)
})

test('论坛在 HTTP 下保留 UUID 回退、标签页草稿和冻结重试语义', () => {
  const forum = source('src/pages/ForumPage.tsx')
  const uuid = source('src/lib/browserUuid.ts')
  assert.doesNotMatch(forum, /crypto\.randomUUID\(/)
  assert.match(forum, /browserUuid\(\)/)
  assert.match(uuid, /getRandomValues/)
  assert.match(forum, /window\.sessionStorage/)
  assert.match(forum, /pending_attempt/)
  assert.match(forum, /FORUM_RETRY_DELAYS = \[350, 900, 1800\]/)
  assert.match(forum, /结果尚未确认，内容与请求标识已冻结/)
})

test('打榜赛恢复 revision 轮询、SSE 自动重连和可撤销编辑', () => {
  const ranking = source('src/pages/RankingDetailPage.tsx')
  const overlays = source('src/ranking/RankingDetailOverlays.tsx')
  assert.match(ranking, /refetchInterval: 10000/)
  assert.match(ranking, /refetchOnWindowFocus: 'always'/)
  assert.match(ranking, /maxOutput > contextWindow/)
  assert.match(ranking, /modalDraft/)
  assert.match(ranking, /setModalDraft\(\{\.\.\.rules\[index\]\}\)/)
  const errorHandler = overlays.match(/source\.onerror = \(\) => \{([\s\S]*?)\n    \}/)
  assert.ok(errorHandler)
  assert.doesNotMatch(errorHandler[1], /source\.close\(\)/)
  assert.match(errorHandler[1], /自动重连/)
})

test('VibeHub Player 保留租约异常恢复与 iframe 就绪屏障', () => {
  const player = source('src/pages/VibeHubPlayerPage.tsx')
  assert.match(player, /error\.status === 429/)
  assert.match(player, /heartbeatFailures < 3/)
  assert.match(player, /15_000/)
  assert.match(player, /heartbeatPromise/)
  assert.match(player, /acquireGeneration/)
  assert.match(player, /navigator\.sendBeacon/)
  assert.match(player, /onLoad=\{\(\) => \{if \(runtime\) setFrameReady\(true\)\}\}/)
})

test('全站配置测试会回写容量并经过原生表单校验', () => {
  const config = source('src/pages/SiteConfigPage.tsx')
  assert.match(config, /reportValidity\(\)/)
  assert.match(config, /context_window_tokens: String\(tested\.context_window_tokens\)/)
  assert.match(config, /max_output_tokens: String\(tested\.max_output_tokens\)/)
  assert.match(config, /if \(result\.limits_adjusted\)/)
  assert.match(config, /test_token: tested\.test_token/)
})
