const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '..')
const detailSource = fs.readFileSync(path.join(frontendRoot, 'src/pages/SubmissionDetailPage.tsx'), 'utf8')
const editorSource = fs.readFileSync(path.join(frontendRoot, 'src/components/MonacoEditor.tsx'), 'utf8')

test('提交详情恢复 Jinja 版只读 Monaco、Lean 多文件模型与 AI 标注能力', () => {
  assert.match(detailSource, /<MonacoEditor language="lean4"[\s\S]*readOnly bundle="full"/)
  assert.match(detailSource, /<MonacoEditor language=\{data\.plang \|\| 'matlab'\}[\s\S]*readOnly bundle="full"/)
  assert.match(detailSource, /submission-code-surface submission-code-viewer/)
  assert.match(detailSource, /monaco\.editor\.createModel\(item\.content/)
  assert.match(detailSource, /saveViewState\?\.\(\)/)
  assert.match(detailSource, /restoreViewState\?\.\(viewState\)/)
  assert.match(detailSource, /setDisplayCode:[\s\S]*selectFile\(defaultPath\)/)
  assert.match(detailSource, /submission\.status === 'Unaccepted' \? <AiTutor/)
  assert.match(detailSource, /createDecorationsCollection/)
  assert.match(detailSource, /monaco-ai-issue-underline/)
  assert.match(editorSource, /readOnly/)
  assert.match(editorSource, /onReady/)
})
