import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query'
import {useMemo, useState, type FormEvent} from 'react'

import {apiFetch, errorMessage} from '../api/client'
import type {ApiEnvelope, JsonRecord} from '../api/types'
import {ErrorState, LoadingState} from '../components/PageState'

interface Response extends ApiEnvelope {agent_sessions: JsonRecord[]; harnesses: JsonRecord[] | string[]; endpoints_by_harness: Record<string, JsonRecord[]>; reasoning_efforts_by_harness: Record<string, Array<JsonRecord | string>>; preference?: {harness?: string; endpoint_id?: number}; agent_quota_summary: JsonRecord}

function Choice({value, label, icon, options, onChange}: {value: string; label: string; icon: string; options: Array<{value: string; label: string}>; onChange: (value: string) => void}) {
  const [open, setOpen] = useState(false)
  return <div className={`rk-choice agent-choice${open ? ' open' : ''}`}><input className="rk-choice-value" value={value} readOnly tabIndex={-1} aria-hidden="true" /><button type="button" className="rk-choice-trigger" role="combobox" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)}><span className="rk-choice-trigger-main"><i className={`fas ${icon}`} /><span>{label}</span></span><i className="fas fa-chevron-down rk-choice-caret" /></button><div className="rk-choice-menu" role="listbox">{options.map((option) => <button type="button" className={`rk-choice-option${option.value === value ? ' active' : ''}`} role="option" aria-selected={option.value === value} onClick={() => {onChange(option.value); setOpen(false)}} key={option.value}><span className="rk-choice-option-main"><i className={`fas ${icon}`} /><span><span className="rk-choice-option-name">{option.label}</span></span></span><i className="fas fa-check rk-choice-option-check" /></button>)}</div></div>
}

export default function AgentTasksPage() {
  const queryClient = useQueryClient()
  const result = useQuery({queryKey: ['agent-tasks'], queryFn: () => apiFetch<Response>('/agent/tasks')})
  const [message, setMessage] = useState('')
  const [harness, setHarness] = useState('')
  const [endpointId, setEndpointId] = useState('')
  const harnesses = useMemo(() => (result.data?.harnesses || []).map((item) => typeof item === 'string' ? {value: item, label: item} : {value: String(item.value || item.id || item.name || ''), label: String(item.label || item.name || item.value || '')}), [result.data])
  const selectedHarness = harness || String(result.data?.preference?.harness || harnesses[0]?.value || '')
  const endpoints = result.data?.endpoints_by_harness?.[selectedHarness] || []
  const selectedEndpoint = endpointId || String(result.data?.preference?.endpoint_id || endpoints[0]?.id || '')
  const create = useMutation({mutationFn: () => {const form = new FormData(); form.append('message', message); form.append('harness', selectedHarness); form.append('endpoint_id', selectedEndpoint); form.append('message_id', crypto.randomUUID()); return apiFetch<ApiEnvelope>('/agent/tasks', {method: 'POST', body: form})}, onSuccess: async () => {setMessage(''); await queryClient.invalidateQueries({queryKey: ['agent-tasks']})}})
  if (result.isPending) return <LoadingState label="正在读取 Agent 会话" />
  if (result.isError) return <ErrorState message={result.error.message} />
  const sessions = result.data?.agent_sessions || []
  const submit = (event: FormEvent) => {event.preventDefault(); create.mutate()}
  return <main className="agent-home" data-agent-home>
    <section className="agent-home-hero" aria-labelledby="agentHomeTitle"><div className="agent-home-heading"><span className="agent-home-kicker">NUMERICAL OJ · AGENT</span><h1 id="agentHomeTitle">今天想让 Agent 做什么？</h1></div><form className="agent-composer" onSubmit={submit} autoComplete="off"><label className="visually-hidden" htmlFor="agentMessage">任务内容</label><textarea id="agentMessage" name="message" rows={4} maxLength={100000} placeholder="让 Agent 分析问题、编写代码或整理文件…" value={message} onChange={(event) => setMessage(event.target.value)} required /><div className="agent-composer-footer"><div className="agent-composer-controls"><div className="agent-composer-choice agent-composer-choice--harness"><Choice value={selectedHarness} label={harnesses.find((item) => item.value === selectedHarness)?.label || '选择 Harness'} icon="fa-terminal" options={harnesses} onChange={(value) => {setHarness(value); setEndpointId('')}} /></div><div className="agent-composer-choice agent-composer-choice--endpoint"><Choice value={selectedEndpoint} label={String(endpoints.find((item) => String(item.id) === selectedEndpoint)?.model || '选择模型节点')} icon="fa-microchip" options={endpoints.map((item) => ({value: String(item.id || ''), label: String(item.model || item.label || item.name || '')}))} onChange={setEndpointId} /></div></div><div className="agent-composer-actions"><label className="agent-icon-button" title="添加附件" aria-label="添加附件"><input className="visually-hidden" type="file" multiple /><i className="fas fa-plus" /></label><button className="agent-send-button" type="submit" disabled={!message.trim() || create.isPending} aria-label="创建 Agent 会话"><i className="fas fa-arrow-up" /></button></div></div>{create.isError ? <p className="agent-composer-feedback" role="alert">{errorMessage(create.error)}</p> : null}</form></section>
    <section className="agent-history" aria-labelledby="agentHistoryTitle"><header className="agent-history-heading"><div><span className="agent-history-kicker">RECENT WORK</span><h2 id="agentHistoryTitle">历史会话</h2></div><span>按最近更新排序</span></header><div className="agent-history-list">{sessions.map((session, index) => {const actor = String(session.requested_by || session.created_by || 'numericaloj'); const id = String(session.session_id || session.task_id || index); const status = String(session.status || '').toLowerCase(); return <a className="agent-history-row" href={String(session.detail_url || `/agent/tasks/${id}`)} key={id}><span className="numoj-avatar agent-history-avatar" aria-hidden="true">{actor.slice(0, 2).toUpperCase()}</span><span className="agent-history-main"><strong title={String(session.title || '未命名任务')}>{String(session.title || '未命名任务')}</strong><small><span>{actor}</span><time>{String(session.updated_at || session.created_at || '')}</time>{['running', 'pending'].includes(status) ? <span className="agent-history-live"><i />运行中</span> : null}</small></span><span className="agent-history-runtime agent-history-runtime--harness"><i className="fas fa-terminal" /><span>{String(session.harness_label || session.harness || 'Harness')}</span></span><span className="agent-history-runtime"><i className="fas fa-microchip" /><span>{String(session.endpoint_model || session.model || '模型节点')}</span></span><i className="fas fa-chevron-right agent-history-arrow" /></a>})}{!sessions.length ? <div className="agent-history-empty"><span className="agent-history-empty-mark"><i className="fas fa-terminal" /></span><strong>还没有会话</strong><p>从上面的输入框开始，Agent 的工作记录会留在这里。</p></div> : null}</div></section>
  </main>
}
