import {useQuery} from '@tanstack/react-query'
import {Link, useParams, useSearchParams} from 'react-router-dom'

import {apiFetch, queryString} from '../api/client'
import type {ApiEnvelope, CompetitionSummary, JsonRecord, SubmissionSummary} from '../api/types'
import {ErrorState, LoadingState} from '../components/PageState'
import {useSession} from '../session'

interface Response extends ApiEnvelope {competition: CompetitionSummary & {description?: string}; rendered_description?: string; tab: string; is_admin?: boolean; leaderboard?: JsonRecord[]; user_submissions?: SubmissionSummary[]; matches?: JsonRecord[]; all_submissions?: SubmissionSummary[]; can_submit?: boolean; submit_block_reason?: string}

const nav = [['description', 'fa-file-alt', '比赛描述'], ['submit', 'fa-paper-plane', '提交作品'], ['leaderboard', 'fa-list-ol', '排行榜'], ['matches', 'fa-chess', '对战数据']]

export default function RankingDetailPage() {
  const {competitionId} = useParams()
  const {session} = useSession()
  const [params] = useSearchParams()
  const tab = params.get('tab') || 'description'
  const result = useQuery({queryKey: ['ranking', competitionId, tab], queryFn: () => apiFetch<Response>(`/api/ranking/competitions/${competitionId}${queryString({tab})}`)})
  if (result.isPending) return <LoadingState label="正在进入赛场" />
  if (result.isError) return <ErrorState message={result.error.message} />
  const data = result.data!
  const competition = data.competition
  const scoring = String(competition.scoring_mode || 'absolute').toLowerCase()
  const mode = scoring === 'elo' ? 'ELO' : scoring === 'agent_judge' ? 'AGENT JUDGE' : scoring === 'reverse_judge' ? 'REVERSE JUDGE' : 'ABSOLUTE'
  const isAdmin = Boolean(data.is_admin || session?.user?.is_admin)
  const tabs = [...nav, ...(isAdmin ? [['all_submissions', 'fa-clipboard-list', '所有提交'], ['edit', 'fa-pencil-alt', '编辑比赛']] : [])]
  const rows = data.user_submissions || data.all_submissions || []
  return <section className="ranking-detail-v2 ranking-v2-detail" data-ranking-detail data-ranking-initial-tab={tab} data-ranking-scoring-mode={scoring}>
    <header className="ranking-competition-header"><div className="ranking-competition-heading"><div className="ranking-competition-eyebrow"><Link to="/app/rankings" className="ranking-back-link"><i className="fas fa-arrow-left" /><span>打榜赛列表</span></Link><span>/</span><span>COMPETITION · {Number(competition.is_active) === 1 ? 'LIVE' : 'OFFLINE'}</span></div><div className="ranking-competition-title-line"><span className="ranking-competition-id">#{String(competition.id).padStart(3, '0')}</span><h1>{competition.title}</h1></div></div><div className="ranking-header-facts"><div className="ranking-header-fact"><span>MODE</span><strong>{mode}</strong></div><div className="ranking-header-fact"><span>CREATED</span><strong>{String(competition.created_at || '')}</strong></div><span className={`ranking-status-chip${Number(competition.is_active) === 1 ? '' : ' is-offline'}`}><i /><span>{Number(competition.is_active) === 1 ? 'LIVE' : 'OFFLINE'}</span></span></div><button type="button" className="ranking-mobile-rail-open"><i className="fas fa-sliders-h" /><span>比赛功能</span></button></header>
    <div className="ranking-workspace"><aside className="ranking-function-rail" aria-label="比赛功能"><button type="button" className="ranking-rail-close"><i className="fas fa-times" /></button><nav className="ranking-rail-nav" aria-label="比赛页面"><p className="ranking-rail-group-label">COMPETITION</p>{tabs.slice(0, 4).map(([value, icon, label]) => <Link to={`/app/rankings/${competitionId}${queryString({tab: value})}`} className={`ranking-rail-button${tab === value ? ' active' : ''}`} aria-current={tab === value ? 'page' : undefined} key={value}><i className={`fas ${icon}`} /><span>{label}</span></Link>)}{isAdmin ? <><p className="ranking-rail-group-label is-admin">ADMIN OPERATIONS</p>{tabs.slice(4).map(([value, icon, label]) => <Link to={`/app/rankings/${competitionId}${queryString({tab: value})}`} className={`ranking-rail-button is-admin${tab === value ? ' active' : ''}`} aria-current={tab === value ? 'page' : undefined} key={value}><i className={`fas ${icon}`} /><span>{label}</span></Link>)}</> : null}</nav><section className="ranking-rail-attachments"><p className="ranking-attachment-label">ATTACHMENTS · <span>0</span></p><div className="ranking-attachments-empty">暂无附件</div></section></aside><div className="ranking-content-scroll"><main className="ranking-panel-stage"><div className="ranking-panel-host"><div data-ranking-panel data-ranking-tab={tab}>
      {tab === 'description' ? <section className="ranking-v2-tab ranking-v2-description">{data.rendered_description || competition.description ? <div className="numoj-markdown numoj-problem-code-rendering ranking-description" dangerouslySetInnerHTML={{__html: data.rendered_description || String(competition.description)}} /> : <div className="ranking-v2-empty ranking-v2-empty--document"><i className="fas fa-file-lines" /><strong>暂无比赛描述</strong><span>赛事管理员尚未发布说明文档。</span></div>}</section> : null}
      {tab === 'leaderboard' ? <section className="ranking-v2-tab ranking-v2-leaderboard">{data.leaderboard?.length ? <div className="ranking-v2-leaderboard-scroll"><div className="leaderboard-list">{data.leaderboard.map((row, index) => {const rank = Number(row.rank || index + 1); const score = Number(row.best_score ?? row.score ?? row.rating ?? 0); const max = Number(competition.max_score || 100); return <div className={`leaderboard-row${String(row.username) === session?.user?.username ? ' is-current-user' : ''}`} key={String(row.username || index)}><span className={`lb-rank${rank <= 3 ? ' is-top' : ''}`}>{String(rank).padStart(2, '0')}</span><span className="lb-user"><span className="numoj-avatar lb-avatar" aria-hidden="true">{String(row.username || 'U').slice(0, 2).toUpperCase()}</span><span className="lb-user-copy"><strong className="lb-username"><span>{String(row.username || row.name || '—')}</span>{String(row.username) === session?.user?.username ? <em className="lb-me-badge">YOU</em> : null}</strong><span className="lb-subs">{String(row.submission_count || 0)} SUBMISSIONS</span></span></span><span className="lb-score-bar"><i style={{'--ranking-score-pct': `${Math.min(100, score * 100 / max)}%`} as React.CSSProperties} /></span><span className="lb-score">{score.toFixed(scoring === 'elo' ? 0 : 2)} <small>{scoring === 'elo' ? 'ELO' : `/ ${max}`}</small></span></div>})}</div></div> : <div className="ranking-v2-empty ranking-v2-empty--leaderboard"><i className="fas fa-ranking-star" /><strong>暂无有效成绩</strong><span>等待首位选手完成评测，排名将在这里出现。</span></div>}</section> : null}
      {['submit', 'all_submissions'].includes(tab) ? <section className={`ranking-v2-tab ${tab === 'submit' ? 'ranking-v2-submit' : 'ranking-v2-submissions'}`}>{data.submit_block_reason ? <p className="ranking-submit-block-reason"><i className="fas fa-exclamation-triangle me-2" />{data.submit_block_reason}</p> : null}<div className="submissions-toolbar"><strong>{tab === 'submit' ? '我的提交' : '提交记录'}</strong></div>{rows.length ? <div className="aj-subs">{rows.map((row) => <Link className="aj-sub" to={`/app/submissions/${row.id}`} key={row.id}><div className="aj-sub-r1"><span className="aj-sub-id">#{row.id}</span><span className="aj-sub-user"><strong className="aj-sub-uname">{row.username || session?.user?.username}</strong></span><span className="aj-st"><span className="d" />{row.status || 'Unknown'}</span><span className="aj-sub-score"><b>{row.score ?? '—'}</b><span> / {competition.max_score || 100}</span></span></div></Link>)}</div> : <div className="ranking-v2-empty submissions-empty"><i className="fas fa-inbox" /><strong>暂无提交</strong><span>尚未有选手提交作品。</span></div>}</section> : null}
      {tab === 'matches' ? <section className="ranking-v2-tab"><div className="ranking-v2-empty"><i className="fas fa-chess" /><strong>{data.matches?.length ? `已有 ${data.matches.length} 场对战` : '暂无对战数据'}</strong><span>对战结果将在评测完成后显示。</span></div></section> : null}
      {tab === 'edit' ? <section className="ranking-v2-tab"><div className="ranking-v2-empty"><i className="fas fa-pencil-alt" /><strong>比赛设置</strong><span>完整编辑功能继续由原管理入口提供。</span><a className="btn btn-outline-secondary mt-3" href={`/ranking/${competition.id}/?tab=edit`}>打开设置</a></div></section> : null}
    </div></div></main></div></div>
  </section>
}
