import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query'
import {useMemo, useState} from 'react'

import {apiFetch, errorMessage} from '../api/client'
import type {ApiEnvelope, JsonRecord} from '../api/types'
import {ErrorState, LoadingState} from '../components/PageState'

interface TreeResponse extends ApiEnvelope {entries?: JsonRecord[]; tree?: JsonRecord[]; structure_version?: number}
interface FileResponse extends ApiEnvelope {id?: number; entry_id?: number; filename?: string; relative_path?: string; content?: string; file_version?: number}

function flatten(values: JsonRecord[], depth = 0): Array<JsonRecord & {depth: number}> {return values.flatMap((item) => [{...item, depth}, ...flatten(Array.isArray(item.children) ? item.children as JsonRecord[] : [], depth + 1)])}
function Icon({name}: {name: string}) {return <svg className="repository-icon"><use href={`#repo-icon-${name}`} /></svg>}

export default function RepositoryPage() {
  const queryClient = useQueryClient()
  const [selected, setSelected] = useState<number | null>(null)
  const [draft, setDraft] = useState<string | null>(null)
  const context = useQuery({queryKey: ['repository', 'context'], queryFn: () => apiFetch<ApiEnvelope>('/api/repository/context')})
  const tree = useQuery({queryKey: ['repository', 'tree'], queryFn: () => apiFetch<TreeResponse>('/api/repository/tree')})
  const file = useQuery({queryKey: ['repository', 'file', selected], queryFn: () => apiFetch<FileResponse>(`/api/repository/file/${selected}`), enabled: selected != null})
  const entries = useMemo(() => flatten(tree.data?.entries || tree.data?.tree || []), [tree.data])
  const save = useMutation({mutationFn: () => {if (!file.data) throw new Error('尚未选择文件'); return apiFetch<ApiEnvelope>('/api/repository/file', {method: 'POST', body: JSON.stringify({file_id: file.data.entry_id || file.data.id || selected, content: draft ?? file.data.content ?? '', expected_file_version: file.data.file_version})})}, onSuccess: async () => {setDraft(null); await queryClient.invalidateQueries({queryKey: ['repository']})}})
  if (context.isPending || tree.isPending) return <LoadingState label="正在挂载代码仓库" />
  if (context.isError || tree.isError) return <ErrorState message={(context.error || tree.error)?.message || '代码仓库加载失败'} />
  const content = draft ?? file.data?.content ?? ''
  const name = file.data?.relative_path || file.data?.filename || '尚未打开文件'
  const ext = name.includes('.') ? name.split('.').pop()?.toUpperCase() : '—'
  return <section className="repository-workbench" aria-label="个人代码仓库">
    <svg className="repository-symbols" aria-hidden="true"><symbol id="repo-icon-folder" viewBox="0 0 24 24"><path d="M3 7.5V6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" /></symbol><symbol id="repo-icon-file" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z" /><path d="M14 2v6h6" /></symbol><symbol id="repo-icon-file-plus" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z" /><path d="M12 12v6m-3-3h6" /></symbol><symbol id="repo-icon-chevron" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6" /></symbol><symbol id="repo-icon-more" viewBox="0 0 24 24"><circle cx="5" cy="12" r="1" /><circle cx="12" cy="12" r="1" /><circle cx="19" cy="12" r="1" /></symbol><symbol id="repo-icon-save" viewBox="0 0 24 24"><path d="M5 3h12l2 2v16H5zM8 3v6h8V3m-1 14H9" /></symbol><symbol id="repo-icon-tree" viewBox="0 0 24 24"><path d="M6 4v12m0-7h6m-6 7h6M12 6h8v6h-8zM12 14h8v6h-8z" /></symbol><symbol id="repo-icon-panel" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2" /><path d="M9 4v16" /></symbol><symbol id="repo-icon-search" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></symbol></svg>
    <header className="repository-header"><button className="repository-mobile-files" type="button"><Icon name="panel" /><span>文件</span></button><div className="repository-heading"><p>CODE REPOSITORY · PERSONAL</p><div><h1>代码仓库</h1><span>{entries.length} ENTRIES · PRIVATE</span></div></div><div className="repository-header-actions"><a className="repository-button repository-button-dark" href="/repository"><Icon name="tree" /><span>结构化整理</span></a></div></header>
    <div className="repository-workspace">
      <aside className="repository-files-pane" aria-label="仓库文件"><div className="repository-pane-head"><span className="repository-pane-copy"><span className="repository-pane-label">FILES</span><span className="repository-pane-count">{entries.length}</span></span></div><div className="repository-tree" role="tree">{entries.map((entry, index) => {const id = Number(entry.id || entry.entry_id || 0); const directory = String(entry.kind || entry.type) === 'directory'; return <div className={`repository-tree-row${selected === id ? ' is-active' : ''}`} style={{'--tree-depth': entry.depth, '--tree-indent': `${Math.min(entry.depth, 8) * 13}px`} as React.CSSProperties} data-entry-kind={directory ? 'directory' : 'file'} role="treeitem" aria-level={entry.depth + 1} key={`${id}-${index}`}><span className="repository-tree-toggle is-placeholder" /><span className={`repository-tree-glyph${directory ? '' : ' file'}`}><Icon name={directory ? 'folder' : 'file'} /></span><button className="repository-tree-main" type="button" disabled={directory} onClick={() => {setSelected(id); setDraft(null)}}><span className="repository-tree-name">{String(entry.name || entry.filename || entry.relative_path || 'untitled')}</span></button><button className="repository-tree-menu" type="button" aria-label="文件操作"><Icon name="more" /></button></div>})}{!entries.length ? <div className="repository-tree-empty">仓库还是空的。<br />可以先在原仓库页新建文件。</div> : null}</div><footer className="repository-files-foot"><span>PRIVATE WORKSPACE</span><span>MAX 2 MIB / FILE · 32 MIB TOTAL</span></footer></aside>
      <main className="repository-editor-pane" aria-label="代码编辑器"><header className="repository-editor-bar"><div className="repository-file-tab"><span className="repository-tab-ext">{ext}</span><strong>{name}</strong>{draft != null ? <span className="repository-modified">● MODIFIED</span> : null}</div><div className="repository-editor-actions"><button className="repository-icon-button" type="button" title="保存（Ctrl/Cmd + S）" aria-label="保存文件" disabled={!selected || save.isPending} onClick={() => save.mutate()}><Icon name="save" /></button></div></header><div className="repository-editor-shell"><div className="repository-breadcrumbs"><span>repository</span><span>›</span><b>{name}</b></div>{!selected ? <div className="repository-empty-editor"><span className="repository-empty-mark"><Icon name="file-plus" /></span><strong>从左侧打开文件</strong><p>也可以新建文件，或将一组文件与文件夹直接拖入文件区。</p></div> : file.isPending ? <div className="repository-editor-loading"><span className="math-curve-loader" data-math-curve-loader data-size="lg"><span className="math-curve-loader__label">代码编辑器正在加载</span></span></div> : <div className="repository-editor-stage"><textarea id="repositoryCodeEditor" aria-label="代码仓库编辑器" autoComplete="off" spellCheck={false} value={content} onChange={(event) => setDraft(event.target.value)} /></div>}</div><footer className="repository-editor-status"><span><b>{ext || 'NO FILE'}</b><span>UTF-8</span><span>LF</span></span><span><span>Ln —, Col —</span><b>{save.isPending ? 'SAVING' : save.isError ? 'ERROR' : draft != null ? 'MODIFIED' : 'IDLE'}</b></span></footer>{save.isError ? <div className="repository-toast is-visible"><div><strong>保存失败</strong><p>{errorMessage(save.error)}</p></div></div> : null}</main>
      <aside className="repository-inspector" aria-label="代码结构与语义检索"><div className="repository-inspector-tabs" role="tablist"><button className="active" type="button">OUTLINE</button><button type="button">SEMANTIC</button></div><section className="repository-inspector-panel active"><p className="repository-inspector-note">从当前文件提取结构。选择符号可定位到对应代码行。</p><div className="repository-outline-list"><div className="repository-inspector-empty">打开文件后显示结构。</div></div></section></aside>
    </div>
  </section>
}
