import {useQuery} from '@tanstack/react-query'
import {Link, useParams} from 'react-router-dom'

import {apiFetch} from '../api/client'
import type {ApiEnvelope, JsonRecord, ProblemSummary} from '../api/types'
import {ErrorState, LoadingState} from '../components/PageState'

interface DetailResponse extends ApiEnvelope {submission: {id: number; problem_id: number; problem_title?: string; problem_type?: number; username?: string; status?: string; score?: number; code?: string; prompt_text?: string; generated_from_prompt?: boolean; prompt_generation_error?: string; created_at?: string}; problem?: ProblemSummary; plang?: string; test_points: JsonRecord[]; cached_ai_code_marks?: JsonRecord; submission_latex_html?: string}

function statusClass(value: unknown) {return String(value || 'Unknown').toLowerCase().replaceAll(' ', '-')}
function pointClass(value: unknown) {const status = String(value || 'Unknown'); return status === 'Accepted' ? 'is-accepted' : ['Pending', 'Waiting', 'Running', 'Generating'].includes(status) ? 'is-active' : status === 'Wrong Answer' ? 'is-wrong-answer' : status === 'Runtime Error' ? 'is-runtime-error' : status === 'Time Limit Exceeded' ? 'is-time-limit' : 'is-failed'}

export default function SubmissionDetailPage() {
  const {submissionId} = useParams()
  const result = useQuery({queryKey: ['submission', submissionId], queryFn: () => apiFetch<DetailResponse>(`/api/submissions/${submissionId}`), refetchInterval: (query) => {const status = (query.state.data as DetailResponse | undefined)?.submission.status; return status && ['Pending', 'Running', 'Generating'].includes(status) ? 2_000 : false}})
  if (result.isPending) return <LoadingState label="正在读取提交快照" />
  if (result.isError) return <ErrorState message={result.error.message} />
  const data = result.data!
  const submission = data.submission
  const programming = Number(submission.problem_type || data.problem?.type || 1) === 1
  const maxScore = programming ? data.test_points.length || Number(data.problem?.max_score || 0) || '?' : 5
  const accepted = submission.score != null && String(submission.score) === String(maxScore)
  return <div className="submission-detail-page" data-math-curve-stroke-scale="1.2">
    <section className="submission-detail-primary" aria-label={programming ? '提交代码' : '书面作业'}>{programming ? <div className="submission-code-surface"><textarea id="submissionCode" readOnly value={submission.code || ''} aria-label="提交代码，只读" /></div> : <div className="submission-pdf-surface"><div className="submission-pdf-hint text-muted">书面作业文件请在原详情入口中查看</div></div>}</section>
    <aside className="submission-detail-summary-card" aria-label="提交摘要"><div className="submission-detail-topline"><Link className="submission-detail-back" to="/app/submissions"><i className="fas fa-arrow-left" /> SUBMISSIONS</Link><span className="submission-detail-id">#{submission.id}</span></div><h1 className="visually-hidden">提交 #{submission.id}</h1><div className="submission-detail-result"><span className={`submission-verdict submission-verdict--${statusClass(submission.status)}`}><span className="submission-verdict__dot" /><span>{submission.status || 'Unknown'}</span></span><div className="submission-detail-score"><strong className={accepted ? 'is-accepted' : submission.score ? 'is-partial' : 'is-failed'}>{submission.score ?? '—'}</strong><span>/ <span>{maxScore}</span></span></div></div><dl className="submission-detail-meta"><dt>题目</dt><dd className="submission-detail-problem-meta"><Link to={`/app/problems/${submission.problem_id}`}>{data.problem?.title || submission.problem_title || '未命名题目'}</Link><span>P{String(submission.problem_id).padStart(4, '0')}</span></dd><dt>提交者</dt><dd>{submission.username}</dd><dt>提交时间</dt><dd>{submission.created_at || '—'}</dd></dl>{submission.generated_from_prompt ? <details className="submission-detail-disclosure submission-prompt-card" open><summary><span>ORIGINAL PROMPT</span><i className="fas fa-chevron-down" /></summary><pre>{submission.prompt_text || ''}</pre>{submission.prompt_generation_error ? <div className="submission-inline-error">{submission.prompt_generation_error}</div> : null}</details> : null}</aside>
    <aside className="submission-detail-results" aria-label={programming ? '测试点详情' : '批改详情'}>{programming ? <section className="submission-detail-section"><header className="submission-detail-section-heading"><div><span>TEST POINTS</span></div></header><div className="test-point-grid">{data.test_points.map((point, index) => <button className={`test-point-card ${pointClass(point.status)}`} type="button" title={`测试点 #${index + 1} · ${String(point.status || 'Unknown')}`} aria-label={`测试点 ${index + 1}，${String(point.status || 'Unknown')}`} key={index}><span className="tp-index">{String(index + 1).padStart(2, '0')}</span>{pointClass(point.status) === 'is-active' ? <span className="math-curve-loader" data-math-curve-loader data-icon-only="true" data-size="xs" /> : null}</button>)}</div>{!data.test_points.length ? <div className="submission-test-detail-hint">判题中，暂时没有可展示的测试点结果。</div> : null}{data.cached_ai_code_marks ? <section className="submission-detail-section submission-ai-section"><header className="submission-detail-section-heading"><div><span>AI TUTOR</span><h2>代码诊断</h2></div></header><pre className="tp-detail-pre">{JSON.stringify(data.cached_ai_code_marks, null, 2)}</pre></section> : null}</section> : <section className="submission-detail-section"><header className="submission-detail-section-heading"><div><span>GRADING</span><h2>批改结果</h2></div></header>{data.submission_latex_html ? <div className="submission-written-comment numoj-markdown" dangerouslySetInnerHTML={{__html: data.submission_latex_html}} /> : <div className="submission-test-detail-hint">暂无可展示的转写内容。</div>}</section>}</aside>
  </div>
}
